<?php 
namespace RW940cms\Services;


/**
* 
*/
class ErroPagseuroService{
	

 public function consultaErro($code){


 	$arrayErros = array("erro_5003"=>"Falha de comunicação com a instituição financeira",
"erro_10000"=>"marca de cartão de crédito inválida",
"erro_10001"=>"número de cartão de crédito com comprimento inválido",
"erro_10002"=>"Formato de data inválido",
"erro_10003"=>"campo de segurança inválido",
"erro_10004"=>"cvv é obrigatório",
"erro_10006"=>"campo de segurança com comprimento inválido",
"erro_53004"=>"quantidade inválida de itens",
"erro_53005"=>"é necessária uma moeda",
"erro_53006"=>"Valor inválido da moeda",
"erro_53007"=>"Referência comprimento inválido",
"erro_53008"=>"notificationURL comprimento inválido",
"erro_53009"=>"notificationURL valor inválido",
"erro_53010"=>"o e-mail do remetente é necessário",
"erro_53011"=>"E-mail do remetente: comprimento inválido",
"erro_53012"=>"Valor inválido do e-mail do remetente",
"erro_53013"=>"O nome do remetente é obrigatório",
"erro_53014"=>"nome inválido duração inválida",
"erro_53015"=>"nome do remetente valor inválido",
"erro_53017"=>"Valor inválido cpf remetente",
"erro_53018"=>"é necessário o código de área do remetente",
"erro_53019"=>"código de área do remetente valor inválido",
"erro_53020"=>"O telefone do remetente é necessário",
"erro_53021"=>"Valor inválido do remetente do telefone",
"erro_53022"=>"é necessário o código postal do endereço de entrega",
"erro_53023"=>"código postal código postal valor inválido",
"erro_53024"=>"O endereço de entrega é obrigatório",
"erro_53025"=>"endereço de entrega rua comprimento inválido",
"erro_53026"=>"é necessário o número do endereço de entrega",
"erro_53027"=>"número de endereço de remessa comprimento inválido",
"erro_53028"=>"comprimento do preenchimento do preenchimento do endereço de remessa",
"erro_53029"=>"O endereço do endereço é obrigatório",
"erro_53030"=>"endereço de entrega distrito inválido",
"erro_53031"=>"endereço de entrega cidade é obrigatório",
"erro_53032"=>"endereço de entrega cidade comprimento inválido",
"erro_53033"=>"O estado do endereço de remessa é obrigatório",
"erro_53034"=>"endereço de envio valor inválido inválido",
"erro_53035"=>"O endereço de entrega do país é obrigatório",
"erro_53036"=>"endereço de envio país inválido comprimento",
"erro_53037"=>"é necessário um token de cartão de crédito",
"erro_53038"=>"quantidade de parcela é necessária",
"erro_53039"=>"quantidade inválida valor inválido",
"erro_53040"=>"O valor da parcela é necessário",
"erro_53041"=>"Valor inválido valor inválido",
"erro_53042"=>"O nome do titular do cartão de crédito é obrigatório",
"erro_53043"=>"Nome do titular do cartão de crédito inválido comprimento",
"erro_53044"=>"Nome do titular do cartão de crédito valor inválido",
"erro_53045"=>"O titular do cartão de crédito cpf é obrigatório",
"erro_53046"=>"titular do cartão de crédito cpf valor inválido",
"erro_53047"=>"A data de nascimento do cartão de crédito é necessária",
"erro_53048"=>"titular do cartão de crédito data de nascimento valor inválido",
"erro_53049"=>"O código de área do titular do cartão de crédito é obrigatório",
"erro_53050"=>"código de área de suporte do cartão de crédito valor inválido",
"erro_53051"=>"O telefone do titular do cartão de crédito é obrigatório",
"erro_53052"=>"Valor do cartão do cartão de crédito do valor inválido",
"erro_53053"=>"É necessário o código postal do endereço de cobrança",
"erro_53054"=>"endereço de cobrança código postal valor inválido",
"erro_53055"=>"Endereço obrigatório é obrigatório",
"erro_53056"=>"endereço de cobrança rua comprimento inválido",
"erro_53057"=>"É necessário o número do endereço de cobrança",
"erro_53058"=>"número de endereço de cobrança número inválido",
"erro_53059"=>"endereço de cobrança complementar comprimento inválido",
"erro_53060"=>"O endereço de cobrança é obrigatório",
"erro_53061"=>"endereço de cobrança distrito inválido comprimento",
"erro_53062"=>"é necessária a cidade de endereço de cobrança",
"erro_53063"=>"endereço de cobrança cidade comprimento inválido",
"erro_53064"=>"O estado do endereço de cobrança é obrigatório",
"erro_53065"=>"endereço de cobrança indicar valor inválido",
"erro_53066"=>"endereço obrigatório país é obrigatório",
"erro_53067"=>"endereço de cobrança país inválido comprimento",
"erro_53068"=>"email do destinatário comprimento inválido",
"erro_53069"=>"Valor inválido do e-mail do destinatário",
"erro_53070"=>"é necessário o ID do item",
"erro_53071"=>"ID inválido comprimento inválido",
"erro_53072"=>"A descrição do item é necessária",
"erro_53073"=>"descrição do item comprimento inválido",
"erro_53074"=>"a quantidade do item é necessária",
"erro_53075"=>"Quantidade do item fora do alcance",
"erro_53076"=>"Valor inválido da quantidade do item",
"erro_53077"=>"o valor do item é necessário",
"erro_53078"=>"Valor inválido do valor do item",
"erro_53079"=>"Valor do item fora do alcance",
"erro_53081"=>"O remetente está relacionado ao receptor",
"erro_53084"=>"receptor inválido, verifique o status da conta do destinatário e se é uma conta do vendedor",
"erro_53085"=>"método de pagamento indisponível",
"erro_53086"=>"quantidade total do carrinho fora do alcance",
"erro_53087"=>"dados inválidos do cartão de crédito",
"erro_53091"=>"O inválido hash não é válido",
"erro_53092"=>"A marca do cartão de crédito não é aceita",
"erro_53095"=>"tipo de envio padrão inválido",
"erro_53096"=>"padrão de custo de transporte inválido",
"erro_53097"=>"custos de envio fora do alcance",
"erro_53098"=>"O valor total do carrinho é negativo",
"erro_53099"=>"Patente inválida de montante extra",
"erro_53101"=>"valor inválido do modo de pagamento, valores válidos são padrão e gateway",
"erro_53102"=>"Valor inválido do método de pagamento, valores válidos são creditCard, boleto e eft",
"erro_53104"=>"O custo de envio foi fornecido, o endereço de envio deve estar completo",
"erro_53105"=>"A informação do remetente foi fornecida, o e-mail também deve ser fornecido",
"erro_53106"=>"O titular do cartão de crédito está incompleto",
"erro_53109"=>"Informações de endereço de remessa foram fornecidas, o e-mail do remetente também deve ser fornecido",
"erro_53110"=>"EFT Bank é necessário",
"erro_53111"=>"EFF Bank não é aceito",
"erro_53115"=>"Valor inválido da data de nascimento do remetente",
"erro_53117"=>"Valor inválido cnpj remetente",
"erro_53122"=>"email do remetente domínio inválido Você deve usar um email @ sandboxpagsegurocombr",
"erro_53140"=>"Quantidade da parcela fora do alcance O valor deve ser maior que zero",
"erro_53141"=>"o remetente está bloqueado",
"erro_53142"=>"token do cartão de crédito inválido");

return $arrayErros['erro_'.$code];
 }
	
	
	
	
}
?>